name: flutter_2026_eric
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/BratishkaErik/flutter-2026-Eric

environment:
  sdk: ^3.13.3

# Add regular dependencies here.
dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
